// Generated by move: sign_up -> auth app pages
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter/services.dart';
import 'package:flutter/gestures.dart';

import '../../../../widgets/app_text_feild.dart';
import '../../../../widgets/app_button.dart';
import '../../../../utils/constants/app_language.dart';
import '../../../../utils/constants/app_text_styles.dart';
import '../../../../utils/constants/app_dimensions.dart';
import '../../../../widgets/flag_image.dart';
// svg import removed; use material Icon for arrow to ensure visibility
import '../../sign_up/sign_up_cubit.dart';
import '../../sign_up/sign_up_state.dart';

class SignUpPage extends StatelessWidget {
  const SignUpPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => SignUpCubit(),
      child: const _SignUpView(),
    );
  }
}

// A custom clipper which creates a centered top arc (a single curve) for the
// top edge of the clipped widget. curveHeight controls how deep the arc is.
class _TopCurveClipper extends CustomClipper<Path> {
  final double curveHeight;
  _TopCurveClipper({this.curveHeight = AppDimensions.panelCurveHeight});

  @override
  Path getClip(Size size) {
    final Path path = Path();

    // Start at the top-left corner. The curve will be drawn below the top
    // edge so we avoid any negative coordinates which would cause the arc to
    // render above the container and visually overflow.
    path.moveTo(0, 0);
    // Move down to the point where the arc should begin
    path.lineTo(0, curveHeight);

    // Draw a quadratic bezier from left to right across the top with a control
    // point at the top edge (y = 0). This keeps the whole curve within the
    // container bounds and prevents the arc from extending above the screen.
    final double cx = size.width / 2;
    path.quadraticBezierTo(cx, 0, size.width, curveHeight);

    // Continue to bottom-right and close
    path.lineTo(size.width, 0);
    path.lineTo(size.width, size.height);
    path.lineTo(0, size.height);
    path.close();

    return path;
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) => false;
}

class _SignUpView extends StatefulWidget {
  const _SignUpView({Key? key}) : super(key: key);

  @override
  State<_SignUpView> createState() => _SignUpViewState();
}

class _SignUpViewState extends State<_SignUpView> with WidgetsBindingObserver {
  final _phoneController = TextEditingController();
  // Four controllers/nodes for separate OTP boxes
  final List<TextEditingController> _otpControllers = List.generate(4, (_) => TextEditingController());
  final List<FocusNode> _otpFocusNodes = List.generate(4, (_) => FocusNode());
  final FocusNode _phoneFocusNode = FocusNode();
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  // track previous raw viewInsets bottom (physical pixels) to detect keyboard hide
  double _prevViewInsetsBottom = 0.0;

  @override
  void dispose() {
    _phoneController.dispose();
    for (final c in _otpControllers) {
      c.dispose();
    }
    for (final n in _otpFocusNodes) {
      n.dispose();
    }
    _phoneFocusNode.dispose();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _prevViewInsetsBottom = WidgetsBinding.instance.window.viewInsets.bottom;
    // Rebuild when focus changes so the AnimatedSwitcher updates automatically.
    _phoneFocusNode.addListener(() => setState(() {}));
    // Ensure OTP focus nodes also trigger rebuilds so underline colors update
    for (final fn in _otpFocusNodes) {
      fn.addListener(() => setState(() {}));
    }
  }

  @override
  void didChangeMetrics() {
    // Called when window metrics change (e.g., keyboard show/hide).
    final bottom = WidgetsBinding.instance.window.viewInsets.bottom;
    // If keyboard just went away, ensure the phone field loses focus.
    if (_prevViewInsetsBottom > 0 && bottom == 0) {
      if (_phoneFocusNode.hasFocus) {
        _phoneFocusNode.unfocus();
        // setState to update UI (AnimatedSwitcher will hide button)
        setState(() {});
      }
    }
    _prevViewInsetsBottom = bottom;
    super.didChangeMetrics();
  }

  @override
  Widget build(BuildContext context) {
  final cubit = context.read<SignUpCubit>();
  // Watch state so we can lock the panel expanded when entering OTP
  final signUpState = context.watch<SignUpCubit>().state;
    return Scaffold(
      body: LayoutBuilder(
        builder: (context, constraints) {
      // Ensure a clearly contrasting panel color: pick an explicit grey
      // dependent on theme brightness so it's visible over the background.
      final brightness = Theme.of(context).colorScheme.brightness;
      final panelColor = brightness == Brightness.light
        ? const Color(0xFFECECEC) // visible light grey on white background
        : const Color(0xFF262626); // visible dark grey on dark background
          final fullHeight = MediaQuery.of(context).size.height;
          // content top padding inside the panel (previously spacingXXL)
          final contentTopPadding = AppDimensions.spacingXXL;

          // half-screen top coordinate when collapsed
          final halfTop = fullHeight * 0.5;
          // compute status bar inset so we can move the panel slightly above
          // the top edge when expanded, making it truly full-screen.
          final statusBar = MediaQuery.of(context).padding.top;

          // When focused or when we're in OTP entry, expand to fill the screen
          // (move up by statusBar so the panel covers the system status bar).
          // Otherwise collapse to half screen.
          final bool shouldExpand = _phoneFocusNode.hasFocus || signUpState.status == VerificationStatus.enteringOtp;
          final targetTop = shouldExpand ? -statusBar : halfTop;

          // When expanded we want no top curve so the panel reads as a
          // full-screen rectangle. Use dynamic curve height for the clipper.
          final panelCurveHeight = shouldExpand ? 0.0 : AppDimensions.panelCurveHeight;

          // Clip the whole area to avoid any visual overflow when the panel
          // animates; paint the top area with the app background so the panel
          // surfaceVariant reads as a distinct layer.
          final topBg = Theme.of(context).colorScheme.background;

          // Allow stack children to paint outside bounds so the panel can
          // animate above the top (covering the status bar). Previously a
          // ClipRect prevented this and clipped the negative top offset.
          return Stack(
            clipBehavior: Clip.none,
            children: [
                // Top background area: a neutral/grey surface
                Positioned.fill(child: Container(color: topBg)),

                // Hero illustration in the top half (visible when panel is collapsed).
                // Add vertical padding so it doesn't touch system UI, and keep it
                // below the panel until the panel expands to top=0 and covers it.
                Positioned(
                  top: 0,
                  left: 0,
                  right: 0,
                  height: halfTop,
                  child: SafeArea(
                    child: Padding(
                      padding: const EdgeInsets.only(top: AppDimensions.spacingXXL, bottom: AppDimensions.spacingS, left: AppDimensions.spacingL, right: AppDimensions.spacingL),
                      child: Center(
                        child: SvgPicture.asset(
                          'assets/images/hero/phone_number_hero.svg',
                          fit: BoxFit.contain,
                          // give the SVG room but keep it inside the top half
                          height: halfTop - AppDimensions.spacingM * 2,
                          semanticsLabel: 'Hero illustration',
                        ),
                      ),
                    ),
                  ),
                ),

              // Bottom curved container that holds the form — clipped to a centered top arc
              // Animated panel: expands to full screen when the phone field gains focus
              AnimatedPositioned(
                duration: const Duration(milliseconds: 280),
                curve: Curves.easeInOut,
                left: 0,
                right: 0,
                top: targetTop,
                bottom: 0,
                child: ClipPath(
                  clipper: _TopCurveClipper(curveHeight: panelCurveHeight),
                  child: Container(
                    decoration: BoxDecoration(
                      color: panelColor,
                      // subtle top border and shadow to increase separation from the hero
                      border: Border(top: BorderSide(color: Theme.of(context).colorScheme.onSurface.withOpacity(0.06))),
                      boxShadow: [
                        BoxShadow(color: Colors.black26, blurRadius: AppDimensions.panelShadowBlur, offset: Offset(0, -AppDimensions.panelShadowOffsetY)),
                      ],
                    ),
                    child: Builder(builder: (context) {
                      // ensure content sits below the curved arc. The clipper uses
                      // curveHeight = 80, so make top padding at least that value
                      // plus a small spacing to avoid overlap.
                      final double curveH = panelCurveHeight;
                      // When expanded (focused), increase top padding so the content
                      // is pushed down and not crowded by the status bar.
                      final bool expanded = _phoneFocusNode.hasFocus || signUpState.status == VerificationStatus.enteringOtp;
                      final topPadding = contentTopPadding + curveH + AppDimensions.spacing - AppDimensions.panelTopOffset + (expanded ? AppDimensions.panelExpandedExtra : 0.0);

                      return Padding(
                        padding: EdgeInsets.fromLTRB(AppDimensions.panelHorizontalPadding, topPadding, AppDimensions.panelHorizontalPadding, AppDimensions.panelBottomPadding),
                        child: BlocBuilder<SignUpCubit, SignUpState>(
                          builder: (context, state) {
                            return SingleChildScrollView(
                              physics: const BouncingScrollPhysics(),
                              child: ConstrainedBox(
                                constraints: BoxConstraints(minHeight: constraints.maxHeight - topPadding - AppDimensions.panelBottomPadding),
                                child: IntrinsicHeight(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: <Widget>[
                                      // Switch title/subtitle depending on verification status
                                      Text(
                                        state.status == VerificationStatus.enteringOtp ? AppLanguage.verifyNumber : AppLanguage.phoneNumberTitle,
                                        style: AppTextStyles.headline1,
                                      ),
                                      const SizedBox(height: 8),
                                      Text(
                                        state.status == VerificationStatus.enteringOtp ? AppLanguage.codeSent : AppLanguage.phoneNumberSubtitle,
                                        style: AppTextStyles.body,
                                      ),
                                      const SizedBox(height: 12),

                                      // Form around the phone field to support validation
                                      Form(
                                        key: _formKey,
                                        child: state.status == VerificationStatus.enteringOtp
                                            ? Padding(
                                                padding: const EdgeInsets.symmetric(horizontal: 8.0),
                                                child: Column(
                                                  children: [
                                                    // Four separate OTP boxes
                                                    Row(
                                                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                                                      children: [
                                                        for (int i = 0; i < 4; i++)
                                                          SizedBox(
                                                            width: AppDimensions.otpBoxWidth,
                                                            child: Container(
                                                              decoration: BoxDecoration(
                                                                border: Border(
                                                                  bottom: BorderSide(
                                                                    color: _otpControllers[i].text.isEmpty
                                                                        ? Theme.of(context).hintColor
                                                                        : (_otpFocusNodes[i].hasFocus ? Theme.of(context).colorScheme.primary : Colors.black),
                                                                    width: AppDimensions.otpUnderlineThickness,
                                                                  ),
                                                                ),
                                                              ),
                                                              child: TextFormField(
                                                                controller: _otpControllers[i],
                                                                focusNode: _otpFocusNodes[i],
                                                                keyboardType: TextInputType.number,
                                                                textAlign: TextAlign.center,
                                                                style: AppTextStyles.headline1.copyWith(fontSize: AppDimensions.otpFontSize),
                                                                inputFormatters: [FilteringTextInputFormatter.digitsOnly, LengthLimitingTextInputFormatter(1)],
                                                                decoration: InputDecoration(
                                                                  hintText: '0',
                                                                  hintStyle: TextStyle(color: Theme.of(context).hintColor),
                                                                  border: InputBorder.none,
                                                                  counterText: '',
                                                                  contentPadding: EdgeInsets.symmetric(vertical: AppDimensions.otpBoxVerticalPadding),
                                                                ),
                                                                onChanged: (val) {
                                                                  if (val.length > 1) {
                                                                    final chars = val.split('');
                                                                    for (var k = 0; k < chars.length && (i + k) < 4; k++) {
                                                                      _otpControllers[i + k].text = chars[k];
                                                                    }
                                                                    final next = (i + chars.length) < 4 ? (i + chars.length) : 3;
                                                                    _otpFocusNodes[next].requestFocus();
                                                                    setState(() {});
                                                                    return;
                                                                  }
                                                                  if (val.isNotEmpty) {
                                                                    final next = i + 1;
                                                                    if (next < 4) {
                                                                      _otpFocusNodes[next].requestFocus();
                                                                    } else {
                                                                      _otpFocusNodes[i].unfocus();
                                                                    }
                                                                  } else {
                                                                    final prev = i - 1;
                                                                    if (prev >= 0) {
                                                                      _otpFocusNodes[prev].requestFocus();
                                                                    }
                                                                  }
                                                                  setState(() {});
                                                                },
                                                              ),
                                                            ),
                                                          ),
                                                      ],
                                                    ),
                                                    // validator placeholder for combined OTP
                                                    Builder(builder: (context) => const SizedBox.shrink()),
                                                  ],
                                                ),
                                              )
                                            : AppTextField(
                                                controller: _phoneController,
                                                focusNode: _phoneFocusNode,
                                                keyboardType: TextInputType.phone,
                                                hintText: null,
                                                // validate phone: must be digits and at least 8 chars
                                                validator: (v) {
                                                  final value = v?.trim() ?? '';
                                                  if (value.isEmpty) return AppLanguage.phoneEmptyError;

                                                  // Allow only digits and optional leading +
                                                  final charsPattern = RegExp(r'^\+?[0-9]+$');
                                                  if (!charsPattern.hasMatch(value)) return AppLanguage.phoneInvalidCharactersError;

                                                  // Normalize for checking: remove '+'
                                                  final normalized = value.startsWith('+') ? value.substring(1) : value;

                                                  // Check prefix: Algeria numbers should start with 213 or 0
                                                  if (!(normalized.startsWith('213') || normalized.startsWith('0'))) {
                                                    return AppLanguage.phoneInvalidPrefixError;
                                                  }

                                                  // After prefix, check expected length
                                                  if (normalized.startsWith('213')) {
                                                    if (normalized.length != 12) return AppLanguage.phoneInvalidLengthError;
                                                  } else if (normalized.startsWith('0')) {
                                                    if (normalized.length != 10) return AppLanguage.phoneInvalidLengthError;
                                                  }

                                                  // Final strict pattern for Algerian numbers
                                                  final pattern = RegExp(r'^(?:\+213|0)(5|6|7)[0-9]{8}$');
                                                  if (!pattern.hasMatch(value)) return AppLanguage.phoneInvalidError;
                                                  return null;
                                                },
                                                autovalidateMode: AutovalidateMode.disabled,
                                                leading: SizedBox(
                                                  width: AppDimensions.flagButtonWidth,
                                                  child: Padding(
                                                    padding: const EdgeInsets.only(left: 8.0, right: 8.0),
                                                    child: _FlagButton(
                                                      currentAsset: 'assets/images/flags/algeria.svg',
                                                      onSelected: (asset) => cubit.setCountryCode(asset),
                                                      preserveFocus: _phoneFocusNode,
                                                    ),
                                                  ),
                                                ),
                                                onChanged: (v) => cubit.setPhoneNumber(v),
                                              ),
                                      ),

                                      // Flexible spacer pushes the following content to the bottom
                                      const Spacer(),

                                      // If focused: show consent (or OTP resend message) above the button, then the button.
                                      // Otherwise: the button is hidden and consent sits at the bottom.
                                      if (_phoneFocusNode.hasFocus || state.status == VerificationStatus.enteringOtp) ...[
                                        Align(
                                          alignment: Alignment.center,
                                          child: state.status == VerificationStatus.enteringOtp
                                              ? Padding(
                                                  padding: const EdgeInsets.only(bottom: AppDimensions.spacingXXL),
                                                  child: RichText(
                                                    textAlign: TextAlign.center,
                                                    text: TextSpan(
                                                      style: AppTextStyles.caption.copyWith(color: Theme.of(context).colorScheme.onSurface),
                                                      children: [
                                                        TextSpan(
                                                          text: AppLanguage.noCodeReceived + ' ',
                                                          style: AppTextStyles.caption.copyWith(decoration: TextDecoration.underline, color: Theme.of(context).colorScheme.onSurface),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                )
                                              : RichText(
                                                  textAlign: TextAlign.center,
                                                  text: TextSpan(
                                                    style: AppTextStyles.caption.copyWith(color: Theme.of(context).colorScheme.onSurface),
                                                    children: [
                                                      TextSpan(text: AppLanguage.consentPrefix + ' '),
                                                      TextSpan(
                                                        text: AppLanguage.termsOfUse,
                                                        style: const TextStyle(decoration: TextDecoration.underline),
                                                      ),
                                                      TextSpan(text: ' ' + AppLanguage.and + ' '),
                                                      TextSpan(
                                                        text: AppLanguage.privacyPolicy,
                                                        style: const TextStyle(decoration: TextDecoration.underline),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                        ),
                                        const SizedBox(height: 12),
                                        AnimatedSwitcher(
                                          duration: const Duration(milliseconds: 200),
                                          switchInCurve: Curves.easeOut,
                                          switchOutCurve: Curves.easeIn,
                                          child: SizedBox(
                                            key: const ValueKey('send_button'),
                                            width: double.infinity,
                                            child: AppButton(
                                              text: state.status == VerificationStatus.enteringOtp ? AppLanguage.verifyMyNumber : AppLanguage.sendCode,
                                              onPressed: state.status == VerificationStatus.loading
                                                  ? null
                                                  : () async {
                                                      if (state.status == VerificationStatus.enteringOtp) {
                                                        final otp = _otpControllers.map((c) => c.text.trim()).join();
                                                        if (otp.length < 4) return;
                                                        cubit.verifyOtp(otp);
                                                        return;
                                                      }
                                                      // Validate the form before sending
                                                      final valid = _formKey.currentState?.validate() ?? false;
                                                      if (!valid) return;
                                                      await cubit.sendCode();
                                                    },
                                              isLoading: state.status == VerificationStatus.loading,
                                              height: AppDimensions.buttonHeight,
                                              padding: const EdgeInsets.symmetric(horizontal: AppDimensions.buttonHorizontalPadding),
                                            ),
                                          ),
                                        ),
                                        const SizedBox(height: AppDimensions.spacingXL),
                                      ] else ...[
                                        // Hidden send button
                                        AnimatedSwitcher(
                                          duration: const Duration(milliseconds: 200),
                                          child: const SizedBox.shrink(key: ValueKey('send_button_hidden')),
                                        ),
                                        const SizedBox(height: AppDimensions.spacingXL),
                                        Align(
                                          alignment: Alignment.center,
                                          child: RichText(
                                            textAlign: TextAlign.center,
                                            text: TextSpan(
                                              style: AppTextStyles.caption.copyWith(color: Theme.of(context).colorScheme.onSurface),
                                              children: [
                                                TextSpan(text: AppLanguage.consentPrefix + ' '),
                                                TextSpan(
                                                  text: AppLanguage.termsOfUse,
                                                  style: const TextStyle(decoration: TextDecoration.underline),
                                                ),
                                                TextSpan(text: ' ' + AppLanguage.and + ' '),
                                                TextSpan(
                                                  text: AppLanguage.privacyPolicy,
                                                  style: const TextStyle(decoration: TextDecoration.underline),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ],
                                  ),
                                ),
                              ),
                            );
                          },
                        ),
                      );
                    }),
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );
  }
}

class _CountryCodeSelector extends StatefulWidget {
  final String initial;
  final ValueChanged<String> onChanged;

  const _CountryCodeSelector({Key? key, required this.initial, required this.onChanged}) : super(key: key);

  @override
  State<_CountryCodeSelector> createState() => _CountryCodeSelectorState();
}

class _FlagButton extends StatefulWidget {
  final String currentAsset;
  final ValueChanged<String> onSelected;
  final FocusNode? preserveFocus;

  const _FlagButton({Key? key, required this.currentAsset, required this.onSelected, this.preserveFocus}) : super(key: key);

  @override
  State<_FlagButton> createState() => _FlagButtonState();
}

class _FlagButtonState extends State<_FlagButton> {
  final LayerLink _layerLink = LayerLink();
  OverlayEntry? _overlayEntry;
  final GlobalKey _buttonKey = GlobalKey();

  void _removeOverlay() {
    _overlayEntry?.remove();
    _overlayEntry = null;
  }

  void _showOverlay() {
    // Remember previous focus
    final hadFocus = widget.preserveFocus?.hasFocus ?? false;

    _overlayEntry = OverlayEntry(builder: (context) {
      // compute button height to offset the follower
      double buttonHeight = 0;
      final btnContext = _buttonKey.currentContext;
      if (btnContext != null) {
        final rb = btnContext.findRenderObject();
        if (rb is RenderBox) buttonHeight = rb.size.height;
      }

      return Positioned.fill(
        child: GestureDetector(
          behavior: HitTestBehavior.translucent,
          onTap: () {
            _removeOverlay();
            if (hadFocus && (widget.preserveFocus != null)) {
              Future.microtask(() => widget.preserveFocus!.requestFocus());
            }
          },
          child: Material(
            color: Colors.transparent,
            child: Stack(
              children: [
                CompositedTransformFollower(
                  link: _layerLink,
                  showWhenUnlinked: false,
                  offset: Offset(0, buttonHeight),
                    child: Material(
                    elevation: 8,
                    color: Theme.of(context).cardColor,
                    borderRadius: BorderRadius.circular(8),
                    child: ConstrainedBox(
                      constraints: BoxConstraints(minWidth: AppDimensions.popupMinWidth, maxWidth: AppDimensions.popupMaxWidth),
                      child: IntrinsicWidth(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: List.generate(3, (i) {
                            return InkWell(
                              onTap: () {
                                widget.onSelected('assets/images/flags/algeria.svg');
                                _removeOverlay();
                                if (hadFocus && (widget.preserveFocus != null)) {
                                  Future.microtask(() => widget.preserveFocus!.requestFocus());
                                }
                              },
                              child: Padding(
                                padding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 10.0),
                                child: Row(
                                  children: [
                                    FlagImage.asset('assets/images/flags/algeria.svg', width: AppDimensions.flagImageWidth, height: AppDimensions.flagImageHeight),
                                    const SizedBox(width: 12),
                                    Text('Algeria'),
                                  ],
                                ),
                              ),
                            );
                          }),
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      );
    });

  Overlay.of(context).insert(_overlayEntry!);
  }

  @override
  void dispose() {
    _removeOverlay();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CompositedTransformTarget(
      link: _layerLink,
      child: SizedBox(
        width: double.infinity,
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            key: _buttonKey,
            borderRadius: BorderRadius.circular(8),
            onTapDown: (_) {
              try {
                widget.preserveFocus?.requestFocus();
              } catch (_) {}
            },
            onTap: () {
              // Toggle overlay
              if (_overlayEntry == null) {
                _showOverlay();
              } else {
                _removeOverlay();
              }
            },
            child: LayoutBuilder(
              builder: (context, constraints) {
                const neededWidth = 64.0; // flag(28)+spacing(8)+icon(16)+inner padding(12)
                final content = Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 6.0, vertical: 8.0),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      FlagImage.asset(widget.currentAsset, width: 28, height: 20),
                      const SizedBox(width: 8),
                      Icon(
                        Icons.keyboard_arrow_up,
                        size: 16,
                        color: Theme.of(context).iconTheme.color ?? Colors.red,
                      ),
                    ],
                  ),
                );

                if (constraints.maxWidth.isFinite && constraints.maxWidth < neededWidth) {
                  return FittedBox(fit: BoxFit.scaleDown, alignment: Alignment.centerLeft, child: content);
                }

                // Ensure the entire available width is tappable by placing the
                // content inside a Row that aligns to the start but expands.
                return Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    content,
                    const Spacer(),
                  ],
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

class _CountryCodeSelectorState extends State<_CountryCodeSelector> {
  late String _code;

  final List<Map<String, String>> _options = const [
    {'code': '+213', 'label': 'DZ'},
    {'code': '+33', 'label': 'FR'},
    {'code': '+1', 'label': 'US'},
  ];

  @override
  void initState() {
    super.initState();
    _code = widget.initial;
  }

  @override
  Widget build(BuildContext context) {
    return DropdownButtonHideUnderline(
      child: DropdownButton<String>(
        value: _code,
        items: _options
            .map((e) => DropdownMenuItem(
                  value: e['code'],
                  child: Row(
                    children: [
                      Text(e['label'] ?? ''),
                      const SizedBox(width: 6),
                      Text(e['code'] ?? ''),
                    ],
                  ),
                ))
            .toList(),
        onChanged: (v) {
          if (v == null) return;
          setState(() => _code = v);
          widget.onChanged(v);
        },
      ),
    );
  }
}
