// Generated by move: sign_up -> auth app pages

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter/services.dart';

import '../../../../widgets/app_text_feild.dart';
import '../../../../widgets/app_button.dart';
import '../../../../utils/constants/app_language.dart';
import '../../../../utils/constants/app_text_styles.dart';
import '../../../../utils/constants/app_dimensions.dart';
import '../../../../widgets/flag_image.dart';
// svg import removed; use material Icon for arrow to ensure visibility
import '../../sign_up/sign_up_cubit.dart';
import '../../sign_up/sign_up_state.dart';
import 'package:amerli_app/features/auth/repository/auth_repository_impl.dart';
import 'package:amerli_app/core/config/injection.dart' show sl;
import 'package:amerli_app/core/utils/top_toast.dart';

class SignUpPage extends StatelessWidget {
  const SignUpPage({super.key});

  @override
  Widget build(BuildContext context) {
    // Obtain repository from DI so the ApiService uses the configured baseUrl
    final repo = sl<AuthRepositoryImpl>();

    return BlocProvider(
      create: (_) => SignUpCubit(repository: repo),
      child: const _SignUpView(),
    );
  }
}

// A custom clipper which creates a centered top arc (a single curve) for the
// top edge of the clipped widget. curveHeight controls how deep the arc is.
class _TopCurveClipper extends CustomClipper<Path> {
  final double curveHeight;
  _TopCurveClipper({this.curveHeight = 80});

  @override
  Path getClip(Size size) {
    final Path path = Path();

    // Start at the top-left corner. The curve will be drawn below the top
    // edge so we avoid any negative coordinates which would cause the arc to
    // render above the container and visually overflow.
    path.moveTo(0, 0);
    // Move down to the point where the arc should begin
    path.lineTo(0, curveHeight);

    // Draw a quadratic bezier from left to right across the top with a control
    // point at the top edge (y = 0). This keeps the whole curve within the
    // container bounds and prevents the arc from extending above the screen.
    final double cx = size.width / 2;
    path.quadraticBezierTo(cx, 0, size.width, curveHeight);

    // Continue to bottom-right and close
    path.lineTo(size.width, 0);
    path.lineTo(size.width, size.height);
    path.lineTo(0, size.height);
    path.close();

    return path;
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) => false;
}

class _SignUpView extends StatefulWidget {
  const _SignUpView();

  @override
  State<_SignUpView> createState() => _SignUpViewState();
}

class _SignUpViewState extends State<_SignUpView> with WidgetsBindingObserver {
  final _phoneController = TextEditingController();
  final FocusNode _phoneFocusNode = FocusNode();
  // OTP inputs
  final List<TextEditingController> _otpControllers =
      List.generate(4, (_) => TextEditingController());
  final List<FocusNode> _otpFocusNodes = List.generate(4, (_) => FocusNode());
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  // track previous raw viewInsets bottom (physical pixels) to detect keyboard hide
  double _prevViewInsetsBottom = 0.0;

  @override
  void dispose() {
    _phoneController.dispose();
    _phoneFocusNode.dispose();
    for (final c in _otpControllers) {
      c.dispose();
    }
    for (final f in _otpFocusNodes) {
      f.dispose();
    }
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    // Rebuild when focus changes so the AnimatedSwitcher updates automatically.
    _phoneFocusNode.addListener(() => setState(() {}));
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _prevViewInsetsBottom = View.of(context).viewInsets.bottom;
  }

  // Helper to return to the phone-entry state cleanly.
  void _returnToPhoneEntry(SignUpCubit cubit) {
    cubit.setPhoneNumber(cubit.state.phoneNumber);

    for (final c in _otpControllers) {
      c.clear();
    }
    for (final f in _otpFocusNodes) {
      f.unfocus();
    }

    Future.microtask(() => _phoneFocusNode.requestFocus());
    setState(() {});
  }

  @override
  void didChangeMetrics() {
    if (!mounted) return;
    // Called when window metrics change (e.g., keyboard show/hide).
    final bottom = View.of(context).viewInsets.bottom;
    // If keyboard just went away, ensure the phone field loses focus.
    if (_prevViewInsetsBottom > 0 && bottom == 0) {
      if (_phoneFocusNode.hasFocus) {
        _phoneFocusNode.unfocus();
        // setState to update UI (AnimatedSwitcher will hide button)
        setState(() {});
      }
    }
    _prevViewInsetsBottom = bottom;
    super.didChangeMetrics();
  }

  @override
  Widget build(BuildContext context) {
    final cubit = context.read<SignUpCubit>();
    return Scaffold(
      body: LayoutBuilder(
        builder: (context, constraints) {
          // Observe the current sign-up state so we can lock the panel when
          // the flow enters the OTP verification step.
          final signUpState = context.watch<SignUpCubit>().state;
          // Ensure a clearly contrasting panel color: pick an explicit grey
          // dependent on theme brightness so it's visible over the background.
          // Use the theme's secondary color for the panel background so it aligns
          // with the app's color scheme.
          final panelColor = Theme.of(context).colorScheme.secondary;
          // Use the height provided by the LayoutBuilder constraints so the
          // panel adapts correctly when this page is embedded in other
          // widgets (like a tabbed onboarding flow) and avoid overflow.
          final fullHeight = constraints.maxHeight;
          // content top padding inside the panel (previously spacingXXL)
          final contentTopPadding = AppDimensions.spacingXXL;

          // half-screen top coordinate when collapsed
          final halfTop = fullHeight * 0.5;
          // compute status bar inset so we can move the panel slightly above
          // the top edge when expanded, making it truly full-screen.
          final statusBar = MediaQuery.of(context).padding.top;

          // When focused OR when we're in the OTP verification state, expand
          // to fill the screen (move up by statusBar so the panel covers the
          // system status bar). Otherwise collapse to half screen.
          final bool expanded = _phoneFocusNode.hasFocus ||
              signUpState.status == VerificationStatus.enteringOtp;
          final targetTop = expanded ? -statusBar : halfTop;

          // When expanded we want no top curve so the panel reads as a
          // full-screen rectangle. Use dynamic curve height for the clipper.
          final panelCurveHeight =
              expanded ? 0.0 : AppDimensions.panelCurveHeight;

          // Clip the whole area to avoid any visual overflow when the panel
          // animates; paint the top area with the app background so the panel
          // surfaceVariant reads as a distinct layer.
          final topBg = Theme.of(context).colorScheme.surface;

          // Allow stack children to paint outside bounds so the panel can
          // animate above the top (covering the status bar). Previously a
          // ClipRect prevented this and clipped the negative top offset.
          return Stack(
            clipBehavior: Clip.none,
            children: [
              // Top background area: a neutral/grey surface
              Positioned.fill(child: Container(color: topBg)),

              // Hero illustration in the top half (visible when panel is collapsed).
              // Add vertical padding so it doesn't touch system UI, and keep it
              // below the panel until the panel expands to top=0 and covers it.
              Positioned(
                top: 0,
                left: 0,
                right: 0,
                height: halfTop,
                child: SafeArea(
                  child: Padding(
                    padding: const EdgeInsets.only(
                        top: AppDimensions.spacingXXL,
                        bottom: AppDimensions.spacingS,
                        left: AppDimensions.spacingL,
                        right: AppDimensions.spacingL),
                    child: Center(
                      child: SvgPicture.asset(
                        'assets/images/hero/phone_number_hero.svg',
                        fit: BoxFit.contain,
                        // give the SVG room but keep it inside the top half
                        height: halfTop - AppDimensions.spacingM * 2,
                        semanticsLabel: 'Hero illustration',
                      ),
                    ),
                  ),
                ),
              ),

              // Bottom curved container that holds the form — clipped to a centered top arc
              // Animated panel: expands to full screen when the phone field gains focus
              AnimatedPositioned(
                duration: const Duration(milliseconds: 280),
                curve: Curves.easeInOut,
                left: 0,
                right: 0,
                top: targetTop,
                bottom: 0,
                child: ClipPath(
                  clipper: _TopCurveClipper(curveHeight: panelCurveHeight),
                  child: Container(
                    decoration: BoxDecoration(
                      color: panelColor,
                      // subtle top border and shadow to increase separation from the hero
                      border: Border(
                          top: BorderSide(
                              color: Theme.of(context)
                                  .colorScheme
                                  .onSurface
                                  .withValues(alpha: 0.06))),
                      boxShadow: [
                        BoxShadow(
                            color: Colors.black26,
                            blurRadius: 12,
                            offset: Offset(0, -6)),
                      ],
                    ),
                    child: Builder(builder: (context) {
                      // ensure content sits below the curved arc. The clipper uses
                      // curveHeight = 80, so make top padding at least that value
                      // plus a small spacing to avoid overlap.
                      final double curveH = panelCurveHeight;
                      // When expanded (focused or in OTP stage), increase top padding so the content
                      // is pushed down and not crowded by the status bar.
                      final bool expanded = _phoneFocusNode.hasFocus ||
                          signUpState.status == VerificationStatus.enteringOtp;
                      final double topPadding = expanded
                          ? (contentTopPadding + statusBar)
                          : (curveH + AppDimensions.spacingM);

                      return BlocListener<SignUpCubit, SignUpState>(
                        listenWhen: (previous, current) =>
                            (previous.result != current.result &&
                                current.result == AuthResult.newUser) ||
                            (previous.errorMessage != current.errorMessage &&
                                current.errorMessage != null) ||
                            (previous.otp != current.otp &&
                                current.otp != null) ||
                            (previous.status != current.status &&
                                current.status == VerificationStatus.verified),
                        listener: (context, state) {
                          if (state.errorMessage != null) {
                            TopToast.show(context, state.errorMessage!,
                                isError: true);
                          }

                          if (state.otp != null &&
                              state.status == VerificationStatus.enteringOtp) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(
                                content: Text('OTP Code: ${state.otp}'),
                                duration: const Duration(days: 1),
                                action: SnackBarAction(
                                  label: 'Copy',
                                  onPressed: () {
                                    Clipboard.setData(
                                        ClipboardData(text: state.otp!));
                                    ScaffoldMessenger.of(context)
                                        .hideCurrentSnackBar();
                                  },
                                ),
                              ),
                            );
                          }

                          if (state.status == VerificationStatus.verified) {
                            ScaffoldMessenger.of(context).hideCurrentSnackBar();
                          }

                          // Use post-frame callback to avoid navigator locked / hero scope issues
                          if (state.result == AuthResult.newUser) {
                            debugPrint(
                                "New User Detected : Navigating to Complete Profile");
                            WidgetsBinding.instance.addPostFrameCallback((_) {
                              // Navigate using GoRouter to the dedicated route. The
                              // CompleteProfilePage will be built by the router so we
                              // avoid pushing a second Navigator with the same GlobalKey.
                              GoRouter.of(context).push('/complete-profile',
                                  extra: context.read<SignUpCubit>());
                            });
                          }
                        },
                        child: BlocBuilder<SignUpCubit, SignUpState>(
                          builder: (context, state) {
                            if (state.isForbidden) {
                              return Center(
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    Icon(
                                      Icons.block,
                                      size: 64,
                                      color:
                                          Theme.of(context).colorScheme.error,
                                    ),
                                    const SizedBox(height: 16),
                                    Text(
                                      "Accès interdit",
                                      style: AppTextStyles.headline2,
                                    ),
                                    const SizedBox(height: 8),
                                    Text(
                                      state.errorMessage ??
                                          "Une erreur est survenue.",
                                      textAlign: TextAlign.center,
                                      style: AppTextStyles.body,
                                    ),
                                    const SizedBox(height: 24),
                                    AppButton(
                                      text: "Réessayer",
                                      onPressed: () => cubit.reset(),
                                      width: 200,
                                    ),
                                  ],
                                ),
                              );
                            }

                            if (state.status ==
                                VerificationStatus.verifyingOtp) {
                              return Center(
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    const CircularProgressIndicator(),
                                    const SizedBox(height: 16),
                                    Text(
                                      "Validation...",
                                      style: AppTextStyles.body.copyWith(
                                          fontWeight: FontWeight.w500),
                                    ),
                                  ],
                                ),
                              );
                            }

                            if (state.status ==
                                VerificationStatus.enteringOtp) {
                              return SingleChildScrollView(
                                physics: const NeverScrollableScrollPhysics(),
                                child: ConstrainedBox(
                                  constraints: BoxConstraints(
                                      minHeight: constraints.maxHeight),
                                  child: IntrinsicHeight(
                                    child: Padding(
                                      padding: EdgeInsets.only(
                                        top: topPadding,
                                        left: AppDimensions.spacingL,
                                        right: AppDimensions.spacingL,
                                        bottom: AppDimensions.spacingL,
                                      ),
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            AppLanguage.verifyNumber,
                                            style: AppTextStyles.headline1,
                                          ),
                                          const SizedBox(height: 8),
                                          RichText(
                                            text: TextSpan(
                                              style: AppTextStyles.body
                                                  .copyWith(
                                                      color: Theme.of(context)
                                                          .colorScheme
                                                          .onSurface),
                                              children: [
                                                TextSpan(
                                                    text:
                                                        '${AppLanguage.codeSent} '),
                                                WidgetSpan(
                                                  alignment:
                                                      PlaceholderAlignment
                                                          .middle,
                                                  child: GestureDetector(
                                                    onTap: () =>
                                                        _returnToPhoneEntry(
                                                            cubit),
                                                    child: Row(
                                                      mainAxisSize:
                                                          MainAxisSize.min,
                                                      children: [
                                                        Text(
                                                          '${state.countryCode} ${state.phoneNumber}',
                                                          style: AppTextStyles
                                                              .body
                                                              .copyWith(
                                                            color: Colors.blue,
                                                            decoration:
                                                                TextDecoration
                                                                    .underline,
                                                            decorationColor:
                                                                Colors.blue,
                                                          ),
                                                        ),
                                                        const SizedBox(
                                                            width: 6),
                                                        SvgPicture.asset(
                                                          'assets/icons/edit.svg',
                                                          width: 18,
                                                          height: 18,
                                                          colorFilter:
                                                              const ColorFilter
                                                                  .mode(
                                                                  Colors.blue,
                                                                  BlendMode
                                                                      .srcIn),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                          const SizedBox(height: 24),
                                          Directionality(
                                            textDirection: TextDirection.ltr,
                                            child: Row(
                                              mainAxisAlignment:
                                                  MainAxisAlignment.center,
                                              children: [
                                                for (int index = 0;
                                                    index < 4;
                                                    index++) ...[
                                                  if (index > 0)
                                                    const SizedBox(width: 16),
                                                  SizedBox(
                                                    width: 50,
                                                    height: 60,
                                                    child: KeyboardListener(
                                                      focusNode: FocusNode(),
                                                      onKeyEvent: (event) {
                                                        if (event
                                                                is KeyDownEvent &&
                                                            event.logicalKey ==
                                                                LogicalKeyboardKey
                                                                    .backspace) {
                                                          if (_otpControllers[
                                                                      index]
                                                                  .text
                                                                  .isEmpty &&
                                                              index > 0) {
                                                            _otpFocusNodes[
                                                                    index - 1]
                                                                .requestFocus();
                                                          }
                                                        }
                                                      },
                                                      child: TextField(
                                                        controller:
                                                            _otpControllers[
                                                                index],
                                                        focusNode:
                                                            _otpFocusNodes[
                                                                index],
                                                        keyboardType:
                                                            TextInputType
                                                                .number,
                                                        textAlign:
                                                            TextAlign.center,
                                                        // Remove maxLength to allow pasting multiple chars temporarily
                                                        // maxLength: 1,
                                                        style: AppTextStyles
                                                            .headline2,
                                                        decoration:
                                                            InputDecoration(
                                                          counterText: "",
                                                          filled: true,
                                                          fillColor: Colors
                                                              .transparent,
                                                          contentPadding:
                                                              EdgeInsets.zero,
                                                          border:
                                                              UnderlineInputBorder(
                                                            borderSide: BorderSide(
                                                                color: Theme.of(
                                                                        context)
                                                                    .colorScheme
                                                                    .outline,
                                                                width: 2),
                                                          ),
                                                          enabledBorder:
                                                              UnderlineInputBorder(
                                                            borderSide: BorderSide(
                                                                color: Theme.of(
                                                                        context)
                                                                    .colorScheme
                                                                    .outline
                                                                    .withOpacity(
                                                                        0.5),
                                                                width: 2),
                                                          ),
                                                          focusedBorder:
                                                              UnderlineInputBorder(
                                                            borderSide: BorderSide(
                                                                color: Theme.of(
                                                                        context)
                                                                    .colorScheme
                                                                    .primary,
                                                                width: 3),
                                                          ),
                                                        ),
                                                        onChanged: (value) {
                                                          if (value.length >
                                                              1) {
                                                            // Paste logic
                                                            if (index == 0) {
                                                              for (int i = 0;
                                                                  i < 4;
                                                                  i++) {
                                                                if (i <
                                                                    value
                                                                        .length) {
                                                                  _otpControllers[
                                                                              i]
                                                                          .text =
                                                                      value[i];
                                                                }
                                                              }
                                                              if (value
                                                                      .length >=
                                                                  4) {
                                                                _otpFocusNodes[
                                                                        3]
                                                                    .requestFocus();
                                                                final otp =
                                                                    _otpControllers
                                                                        .map((c) =>
                                                                            c.text)
                                                                        .join();
                                                                cubit.verifyOtp(
                                                                    otp);
                                                              } else {
                                                                _otpFocusNodes[
                                                                        value.length -
                                                                            1]
                                                                    .requestFocus();
                                                              }
                                                            }
                                                            return;
                                                          }
                                                          if (value
                                                              .isNotEmpty) {
                                                            if (index < 3) {
                                                              _otpFocusNodes[
                                                                      index + 1]
                                                                  .requestFocus();
                                                            } else {
                                                              _otpFocusNodes[
                                                                      index]
                                                                  .unfocus();
                                                              final otp =
                                                                  _otpControllers
                                                                      .map((c) =>
                                                                          c.text)
                                                                      .join();
                                                              cubit.verifyOtp(
                                                                  otp);
                                                            }
                                                          }
                                                        },
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ],
                                            ),
                                          ),
                                          const Spacer(),
                                          Center(
                                            child: TextButton(
                                              onPressed: () {
                                                cubit.sendCode();
                                              },
                                              child: Text(
                                                AppLanguage.noCodeReceived,
                                                style:
                                                    AppTextStyles.body.copyWith(
                                                  color: Theme.of(context)
                                                      .primaryColor,
                                                  fontWeight: FontWeight.bold,
                                                ),
                                              ),
                                            ),
                                          ),
                                          const SizedBox(height: 24),
                                          AppButton(
                                            text: AppLanguage.verifyMyNumber,
                                            onPressed: () {
                                              final otp = _otpControllers
                                                  .map((c) => c.text)
                                                  .join();
                                              cubit.verifyOtp(otp);
                                            },
                                            isLoading: state.status ==
                                                VerificationStatus.loading,
                                          ),
                                          const SizedBox(
                                              height: AppDimensions.spacingXL),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                              );
                            }

                            return SingleChildScrollView(
                              physics: const NeverScrollableScrollPhysics(),
                              child: ConstrainedBox(
                                constraints: BoxConstraints(
                                    minHeight: constraints.maxHeight),
                                child: IntrinsicHeight(
                                  child: Padding(
                                    padding: EdgeInsets.only(
                                      top: topPadding,
                                      left: AppDimensions.spacingL,
                                      right: AppDimensions.spacingL,
                                      bottom: AppDimensions.spacingL,
                                    ),
                                    child: Column(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          AppLanguage.phoneNumberTitle,
                                          style: AppTextStyles.headline1,
                                        ),
                                        const SizedBox(height: 8),
                                        Text(
                                          AppLanguage.phoneNumberSubtitle,
                                          style: AppTextStyles.body,
                                        ),
                                        const SizedBox(height: 24),
                                        Form(
                                          key: _formKey,
                                          child: AppTextField(
                                            controller: _phoneController,
                                            focusNode: _phoneFocusNode,
                                            keyboardType: TextInputType.phone,
                                            hintText: null,
                                            validator: (v) {
                                              final value = v?.trim() ?? '';
                                              if (value.isEmpty) {
                                                return AppLanguage
                                                    .phoneEmptyError;
                                              }
                                              final pattern =
                                                  r'^(?:\+213|0)(5|6|7)[0-9]{8}$';
                                              final reg = RegExp(pattern);
                                              if (!reg.hasMatch(value)) {
                                                return AppLanguage
                                                    .phoneInvalidError;
                                              }
                                              return null;
                                            },
                                            autovalidateMode:
                                                AutovalidateMode.disabled,
                                            leading: SizedBox(
                                              width:
                                                  AppDimensions.flagButtonWidth,
                                              child: Padding(
                                                padding:
                                                    const EdgeInsets.symmetric(
                                                        horizontal: 8.0),
                                                child: _FlagButton(
                                                  currentAsset:
                                                      'assets/images/flags/algeria.svg',
                                                  onSelected: (asset) => cubit
                                                      .setCountryCode(asset),
                                                  preserveFocus:
                                                      _phoneFocusNode,
                                                ),
                                              ),
                                            ),
                                            onChanged: (v) =>
                                                cubit.setPhoneNumber(v),
                                          ),
                                        ),
                                        const SizedBox(height: 12),
                                        SizedBox(
                                          height: 60,
                                          child: Center(
                                            child: RichText(
                                              textAlign: TextAlign.center,
                                              text: TextSpan(
                                                style: AppTextStyles.caption
                                                    .copyWith(
                                                        color: Theme.of(context)
                                                            .colorScheme
                                                            .onSurface),
                                                children: [
                                                  TextSpan(
                                                      text:
                                                          '${AppLanguage.consentPrefix} '),
                                                  TextSpan(
                                                    text:
                                                        AppLanguage.termsOfUse,
                                                    style: const TextStyle(
                                                        decoration:
                                                            TextDecoration
                                                                .underline),
                                                  ),
                                                  TextSpan(
                                                      text:
                                                          ' ${AppLanguage.and} '),
                                                  TextSpan(
                                                    text: AppLanguage
                                                        .privacyPolicy,
                                                    style: const TextStyle(
                                                        decoration:
                                                            TextDecoration
                                                                .underline),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                        ),
                                        const Spacer(),
                                        if (_phoneFocusNode.hasFocus) ...[
                                          SizedBox(
                                            width: double.infinity,
                                            child: AppButton(
                                              text: AppLanguage.sendCode,
                                              onPressed: state.status ==
                                                      VerificationStatus.loading
                                                  ? null
                                                  : () async {
                                                      final valid = _formKey
                                                              .currentState
                                                              ?.validate() ??
                                                          false;
                                                      if (!valid) return;
                                                      await cubit.sendCode();
                                                    },
                                              isLoading: state.status ==
                                                  VerificationStatus.loading,
                                              height: 48,
                                            ),
                                          ),
                                          const SizedBox(
                                              height: AppDimensions.spacingXL),
                                        ] else ...[
                                          const SizedBox(
                                              height: AppDimensions.spacingXL),
                                        ],
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                            );
                          },
                        ),
                      );
                    }),
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );
  }
}

class _FlagButton extends StatefulWidget {
  final String currentAsset;
  final ValueChanged<String> onSelected;
  final FocusNode? preserveFocus;

  const _FlagButton(
      {required this.currentAsset,
      required this.onSelected,
      this.preserveFocus});

  @override
  State<_FlagButton> createState() => _FlagButtonState();
}

class _FlagButtonState extends State<_FlagButton> {
  final LayerLink _layerLink = LayerLink();
  OverlayEntry? _overlayEntry;
  final GlobalKey _buttonKey = GlobalKey();
  final List<Map<String, String>> _options = [
    {'code': '+213', 'label': 'DZ'},
    {'code': '+33', 'label': 'FR'},
    {'code': '+1', 'label': 'US'},
  ];

  void _removeOverlay() {
    _overlayEntry?.remove();
    _overlayEntry = null;
  }

  void _showOverlay() {
    // Remember previous focus
    final hadFocus = widget.preserveFocus?.hasFocus ?? false;

    _overlayEntry = OverlayEntry(builder: (context) {
      // compute button height to offset the follower
      double buttonHeight = 0;
      final btnContext = _buttonKey.currentContext;
      if (btnContext != null) {
        final rb = btnContext.findRenderObject();
        if (rb is RenderBox) buttonHeight = rb.size.height;
      }

      return Positioned.fill(
        child: GestureDetector(
          behavior: HitTestBehavior.translucent,
          onTap: () {
            _removeOverlay();
            if (hadFocus && (widget.preserveFocus != null)) {
              Future.microtask(() => widget.preserveFocus!.requestFocus());
            }
          },
          child: Material(
            color: Colors.transparent,
            child: Stack(
              children: [
                CompositedTransformFollower(
                  link: _layerLink,
                  showWhenUnlinked: false,
                  offset: Offset(0, buttonHeight),
                  child: Material(
                    elevation: 8,
                    color: Theme.of(context).cardColor,
                    borderRadius: BorderRadius.circular(8),
                    child: ConstrainedBox(
                      constraints: BoxConstraints(minWidth: 150, maxWidth: 280),
                      child: IntrinsicWidth(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: _options.map((option) {
                            final code = option['code']!;
                            final label = option['label']!;
                            // Map label to flag asset (simplified)
                            String asset = 'assets/images/flags/algeria.svg';
                            String countryName = 'Algeria';
                            if (label == 'FR') {
                              asset = 'assets/images/flags/france.svg';
                              countryName = 'France';
                            } else if (label == 'US') {
                              asset = 'assets/images/flags/usa.svg';
                              countryName = 'USA';
                            }

                            return InkWell(
                              onTap: () {
                                widget.onSelected(asset);
                                _removeOverlay();
                                if (hadFocus &&
                                    (widget.preserveFocus != null)) {
                                  Future.microtask(() =>
                                      widget.preserveFocus!.requestFocus());
                                }
                              },
                              child: Padding(
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 12.0, vertical: 10.0),
                                child: Row(
                                  children: [
                                    // Fallback to algeria if asset not found or use a generic flag widget
                                    // Since we might not have all assets, we'll just use what we have or a placeholder
                                    // For now, we assume assets exist or we reuse algeria for demo if missing
                                    // But user asked for "other countries".
                                    // I'll use a simple icon if flag missing or just text.
                                    // But FlagImage expects asset.
                                    // I'll try to use the asset if I can guess it, otherwise just text.
                                    // Actually, let's just show the code and label.
                                    SizedBox(
                                      width: 28,
                                      height: 20,
                                      child: asset.contains('algeria')
                                          ? FlagImage.asset(asset,
                                              width: 28, height: 20)
                                          : Container(
                                              color: Colors.grey.shade300,
                                              alignment: Alignment.center,
                                              child: Text(label,
                                                  style: TextStyle(
                                                      fontSize: 10,
                                                      fontWeight:
                                                          FontWeight.bold))),
                                    ),
                                    const SizedBox(width: 12),
                                    Text('$countryName ($code)'),
                                  ],
                                ),
                              ),
                            );
                          }).toList(),
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      );
    });

    Overlay.of(context).insert(_overlayEntry!);
  }

  @override
  void dispose() {
    _removeOverlay();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CompositedTransformTarget(
      link: _layerLink,
      child: SizedBox(
        width: double.infinity,
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            key: _buttonKey,
            borderRadius: BorderRadius.circular(8),
            onTapDown: (_) {
              try {
                widget.preserveFocus?.requestFocus();
              } catch (_) {}
            },
            onTap: () {
              // Toggle overlay
              if (_overlayEntry == null) {
                _showOverlay();
              } else {
                _removeOverlay();
              }
            },
            child: FittedBox(
              fit: BoxFit.scaleDown,
              alignment: Alignment.centerLeft,
              child: Padding(
                padding:
                    const EdgeInsets.symmetric(horizontal: 6.0, vertical: 8.0),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    FlagImage.asset(widget.currentAsset, width: 28, height: 20),
                    const SizedBox(width: 8),
                    Icon(
                      Icons.keyboard_arrow_up,
                      size: 16,
                      color: Theme.of(context).iconTheme.color ?? Colors.red,
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
