// Generated by move: sign_up -> auth app pages
import 'package:amerli_app/utils/constants/app_colors.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_svg/flutter_svg.dart';

import '../../../../widgets/app_text_feild.dart';
import '../../../../widgets/app_button.dart';
import '../../../../utils/constants/app_language.dart';
import '../../../../utils/constants/app_text_styles.dart';
import '../../../../utils/constants/app_dimensions.dart';
import '../../../../widgets/flag_image.dart';
// svg import removed; use material Icon for arrow to ensure visibility
import '../../sign_up/sign_up_cubit.dart';
import '../../sign_up/sign_up_state.dart';
import 'package:amerli_app/features/auth/repository/auth_repository_impl.dart';
import 'package:amerli_app/core/config/injection.dart' show sl;

class SignUpPage extends StatelessWidget {
  const SignUpPage({super.key});

  @override
  Widget build(BuildContext context) {
    // Obtain repository from DI so the ApiService uses the configured baseUrl
    final repo = sl<AuthRepositoryImpl>();

    return BlocProvider(
      create: (_) => SignUpCubit(repository: repo),
      child: const _SignUpView(),
    );
  }
}

// A custom clipper which creates a centered top arc (a single curve) for the
// top edge of the clipped widget. curveHeight controls how deep the arc is.
class _TopCurveClipper extends CustomClipper<Path> {
  final double curveHeight;
  _TopCurveClipper({this.curveHeight = 80});

  @override
  Path getClip(Size size) {
    final Path path = Path();

    // Start at the top-left corner. The curve will be drawn below the top
    // edge so we avoid any negative coordinates which would cause the arc to
    // render above the container and visually overflow.
    path.moveTo(0, 0);
    // Move down to the point where the arc should begin
    path.lineTo(0, curveHeight);

    // Draw a quadratic bezier from left to right across the top with a control
    // point at the top edge (y = 0). This keeps the whole curve within the
    // container bounds and prevents the arc from extending above the screen.
    final double cx = size.width / 2;
    path.quadraticBezierTo(cx, 0, size.width, curveHeight);

    // Continue to bottom-right and close
    path.lineTo(size.width, 0);
    path.lineTo(size.width, size.height);
    path.lineTo(0, size.height);
    path.close();

    return path;
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) => false;
}

class _SignUpView extends StatefulWidget {
  const _SignUpView();

  @override
  State<_SignUpView> createState() => _SignUpViewState();
}

class _SignUpViewState extends State<_SignUpView> with WidgetsBindingObserver {
  final _phoneController = TextEditingController();
  final FocusNode _phoneFocusNode = FocusNode();
  // OTP inputs
  final List<TextEditingController> _otpControllers = List.generate(4, (_) => TextEditingController());
  final List<FocusNode> _otpFocusNodes = List.generate(4, (_) => FocusNode());
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  // track previous raw viewInsets bottom (physical pixels) to detect keyboard hide
  double _prevViewInsetsBottom = 0.0;

  @override
  void dispose() {
    _phoneController.dispose();
    _phoneFocusNode.dispose();
    for (final c in _otpControllers) { c.dispose(); }
    for (final f in _otpFocusNodes) { f.dispose(); }
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _prevViewInsetsBottom = WidgetsBinding.instance.window.viewInsets.bottom;
    // Rebuild when focus changes so the AnimatedSwitcher updates automatically.
    _phoneFocusNode.addListener(() => setState(() {}));
  }

  // Helper to return to the phone-entry state cleanly.
  void _returnToPhoneEntry(SignUpCubit cubit) {
    cubit.setPhoneNumber(cubit.state.phoneNumber);

    for (final c in _otpControllers) {
      c.clear();
    }
    for (final f in _otpFocusNodes) {
      f.unfocus();
    }

    Future.microtask(() => _phoneFocusNode.requestFocus());
    setState(() {});
  }

  @override
  void didChangeMetrics() {
    // Called when window metrics change (e.g., keyboard show/hide).
    final bottom = WidgetsBinding.instance.window.viewInsets.bottom;
    // If keyboard just went away, ensure the phone field loses focus.
    if (_prevViewInsetsBottom > 0 && bottom == 0) {
      if (_phoneFocusNode.hasFocus) {
        _phoneFocusNode.unfocus();
        // setState to update UI (AnimatedSwitcher will hide button)
        setState(() {});
      }
    }
    _prevViewInsetsBottom = bottom;
    super.didChangeMetrics();
  }

  @override
  Widget build(BuildContext context) {
    final cubit = context.read<SignUpCubit>();
    return Scaffold(
      body: LayoutBuilder(
        builder: (context, constraints) {
      // Observe the current sign-up state so we can lock the panel when
      // the flow enters the OTP verification step.
      final signUpState = context.watch<SignUpCubit>().state;
      // Ensure a clearly contrasting panel color: pick an explicit grey
      // dependent on theme brightness so it's visible over the background.
      // Use the theme's secondary color for the panel background so it aligns
      // with the app's color scheme.
      final panelColor = Theme.of(context).colorScheme.secondary;
          // Use the height provided by the LayoutBuilder constraints so the
          // panel adapts correctly when this page is embedded in other
          // widgets (like a tabbed onboarding flow) and avoid overflow.
          final fullHeight = constraints.maxHeight;
          // content top padding inside the panel (previously spacingXXL)
          final contentTopPadding = AppDimensions.spacingXXL;

          // half-screen top coordinate when collapsed
          final halfTop = fullHeight * 0.5;
          // compute status bar inset so we can move the panel slightly above
          // the top edge when expanded, making it truly full-screen.
          final statusBar = MediaQuery.of(context).padding.top;

          // When focused OR when we're in the OTP verification state, expand
          // to fill the screen (move up by statusBar so the panel covers the
          // system status bar). Otherwise collapse to half screen.
          final bool expanded = _phoneFocusNode.hasFocus || signUpState.status == VerificationStatus.enteringOtp;
          final targetTop = expanded ? -statusBar : halfTop;

          // When expanded we want no top curve so the panel reads as a
          // full-screen rectangle. Use dynamic curve height for the clipper.
          final panelCurveHeight = expanded ? 0.0 : AppDimensions.panelCurveHeight;

          // Clip the whole area to avoid any visual overflow when the panel
          // animates; paint the top area with the app background so the panel
          // surfaceVariant reads as a distinct layer.
          final topBg = Theme.of(context).colorScheme.surface;

          // Allow stack children to paint outside bounds so the panel can
          // animate above the top (covering the status bar). Previously a
          // ClipRect prevented this and clipped the negative top offset.
          return Stack(
            clipBehavior: Clip.none,
            children: [
                // Top background area: a neutral/grey surface
                Positioned.fill(child: Container(color: topBg)),

                // Hero illustration in the top half (visible when panel is collapsed).
                // Add vertical padding so it doesn't touch system UI, and keep it
                // below the panel until the panel expands to top=0 and covers it.
                Positioned(
                  top: 0,
                  left: 0,
                  right: 0,
                  height: halfTop,
                  child: SafeArea(
                    child: Padding(
                      padding: const EdgeInsets.only(top: AppDimensions.spacingXXL, bottom: AppDimensions.spacingS, left: AppDimensions.spacingL, right: AppDimensions.spacingL),
                      child: Center(
                        child: SvgPicture.asset(
                          'assets/images/hero/phone_number_hero.svg',
                          fit: BoxFit.contain,
                          // give the SVG room but keep it inside the top half
                          height: halfTop - AppDimensions.spacingM * 2,
                          semanticsLabel: 'Hero illustration',
                        ),
                      ),
                    ),
                  ),
                ),

              // Bottom curved container that holds the form — clipped to a centered top arc
              // Animated panel: expands to full screen when the phone field gains focus
              AnimatedPositioned(
                duration: const Duration(milliseconds: 280),
                curve: Curves.easeInOut,
                left: 0,
                right: 0,
                top: targetTop,
                bottom: 0,
                child: ClipPath(
                  clipper: _TopCurveClipper(curveHeight: panelCurveHeight),
                  child: Container(
                    decoration: BoxDecoration(
                      color: panelColor,
                      // subtle top border and shadow to increase separation from the hero
                      border: Border(top: BorderSide(color: Theme.of(context).colorScheme.onSurface.withOpacity(0.06))),
                      boxShadow: [
                        BoxShadow(color: Colors.black26, blurRadius: 12, offset: Offset(0, -6)),
                      ],
                    ),
                    child: Builder(builder: (context) {
                      // ensure content sits below the curved arc. The clipper uses
                      // curveHeight = 80, so make top padding at least that value
                      // plus a small spacing to avoid overlap.
                      final double curveH = panelCurveHeight;
                      // When expanded (focused or in OTP stage), increase top padding so the content
                      // is pushed down and not crowded by the status bar.
                      final bool expanded = _phoneFocusNode.hasFocus || signUpState.status == VerificationStatus.enteringOtp;
                      final topPadding = contentTopPadding + curveH + AppDimensions.spacing - AppDimensions.panelTopOffset + (expanded ? AppDimensions.panelExpandedExtra : 0.0);

                      return Padding(
                        padding: EdgeInsets.fromLTRB(AppDimensions.panelHorizontalPadding, topPadding, AppDimensions.panelHorizontalPadding, AppDimensions.panelBottomPadding),
                          child: BlocListener<SignUpCubit, SignUpState>(
                          // Only react when the result becomes `newUser` — navigation to
                          // home for existing users is handled centrally by the AuthBloc
                          // -> router redirect to avoid concurrent navigator updates.
                          listenWhen: (previous, current) => previous.result != current.result &&
                              current.result == AuthResult.newUser,
                          listener: (context, state) {
                            // Use post-frame callback to avoid navigator locked / hero scope issues
                            if (state.result == AuthResult.newUser) {
                              print("New User Detected : Navigating to Complete Profile");
                              WidgetsBinding.instance.addPostFrameCallback((_) {
                                // Navigate using GoRouter to the dedicated route. The
                                // CompleteProfilePage will be built by the router so we
                                // avoid pushing a second Navigator with the same GlobalKey.
                                GoRouter.of(context).push('/complete-profile', extra: context.read<SignUpCubit>());
                              });
                            }
                          },
                          child: BlocBuilder<SignUpCubit, SignUpState>(
                            builder: (context, state) {
                              // If entering OTP stage, show verification UI; otherwise show phone form
                              if (state.status == VerificationStatus.enteringOtp) {
                                return SingleChildScrollView(
                                  child: ConstrainedBox(
                                    constraints: BoxConstraints(maxHeight: constraints.maxHeight - topPadding),
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                    Text(
                                      AppLanguage.verifyNumber,
                                      style: AppTextStyles.headline1,
                                    ),
                                    const SizedBox(height: 8),
                                    // Message text that ends with the tappable phone number + icon
                                    RichText(
                                      text: TextSpan(
                                        style: AppTextStyles.body.copyWith(color: Theme.of(context).colorScheme.onSurface),
                                        children: [
                                          TextSpan(text: '${AppLanguage.codeSent} '),
                                          WidgetSpan(
                                            alignment: PlaceholderAlignment.middle,
                                            child: GestureDetector(
                                              behavior: HitTestBehavior.opaque,
                                              onTap: () => _returnToPhoneEntry(cubit),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                children: [
                                                  Text(
                                                    '${state.countryCode} ${state.phoneNumber}',
                                                    style: AppTextStyles.body.copyWith(
                                                      color: Colors.blue,
                                                      decoration: TextDecoration.underline,
                                                      decorationColor: Colors.blue,
                                                    ),
                                                  ),
                                                  const SizedBox(width: 6),
                                                  SvgPicture.asset(
                                                    'assets/icons/edit.svg',
                                                    width: 18,
                                                    height: 18,
                                                    color: Colors.blue,
                                                    semanticsLabel: 'Edit phone',
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    const SizedBox(height: 18),
                                    // OTP boxes
                                    Padding(
                                      padding: const EdgeInsets.symmetric(horizontal: 50.0),
                                      child: Row(
                                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                        children: List.generate(4, (i) {
                                          return SizedBox(
                                            width: 56,
                                            child: TextField(
                                              controller: _otpControllers[i],
                                              focusNode: _otpFocusNodes[i],
                                              keyboardType: TextInputType.number,
                                              textAlign: TextAlign.center,
                                              maxLength: 1,
                                              style: TextStyle(fontSize: 24, color: Theme.of(context).colorScheme.primary),
                                              decoration: InputDecoration(
                                                counterText: '',
                                                hintText: '0',
                                                hintStyle: TextStyle(color: AppColors.hint),
                                                enabledBorder: UnderlineInputBorder(
                                                  borderSide: BorderSide(color: AppColors.hint),
                                                ),
                                                focusedBorder: UnderlineInputBorder(
                                                  borderSide: BorderSide(color: Theme.of(context).colorScheme.primary, width: 2),
                                                ),
                                              ),
                                              onChanged: (v) {
                                                if (v.length > 1) {
                                                  // handle paste: distribute characters
                                                  final chars = v.split('');
                                                  for (var j = 0; j < chars.length && (i + j) < 4; j++) {
                                                    _otpControllers[i + j].text = chars[j];
                                                  }
                                                  final next = (i + chars.length).clamp(0, 4);
                                                  if (next < 4) _otpFocusNodes[next].requestFocus();
                                                } else {
                                                  if (v.isNotEmpty) {
                                                    if (i < 3) _otpFocusNodes[i + 1].requestFocus();
                                                  } else {
                                                    if (i > 0) _otpFocusNodes[i - 1].requestFocus();
                                                  }
                                                }
                                              },
                                            ),
                                          );
                                        }),
                                      ),
                                    ),
                                    const SizedBox(height: 12),
                                    Center(
                                      child: GestureDetector(
                                        onTap: () async {
                                          // resend code
                                          await cubit.sendCode();
                                        },
                                        child: Text(
                                          AppLanguage.noCodeReceived,
                                          textAlign: TextAlign.center,
                                          style: AppTextStyles.caption.copyWith(
                                            color: Theme.of(context).colorScheme.primary,
                                            decoration: TextDecoration.underline,
                                          ),
                                        ),
                                      ),
                                    ),
                                    const Spacer(),
                                    // Ensure the verify button is placed above system
                                    // navigation (soft buttons) by using SafeArea.
                                    SafeArea(
                                      top: false,
                                      minimum: const EdgeInsets.only(bottom: 24.0),
                                      child: SizedBox(
                                        width: double.infinity,
                                        child: AppButton(
                                          text: AppLanguage.verifyMyNumber,
                                          onPressed: () {
                                            final code = _otpControllers.map((c) => c.text).join();
                                            if (code == '0000') {
                                              // Special-case debug code
                                              print('valid');
                                            } else {
                                              cubit.verifyOtp(code);
                                            }
                                          },
                                          height: 48,
                                        ),
                                      ),
                                    ),
                                  ],
                                    ),
                                  ),
                                );
                              }

                              // Phone entry form (existing)
                              return SingleChildScrollView(
                                child: ConstrainedBox(
                                  constraints: BoxConstraints(maxHeight: constraints.maxHeight - topPadding),
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                  Text(
                                    AppLanguage.phoneNumberTitle,
                                    style: AppTextStyles.headline1,
                                  ),
                                  const SizedBox(height: 8),
                                  Text(
                                    AppLanguage.phoneNumberSubtitle,
                                    style: AppTextStyles.body,
                                  ),
                                  const SizedBox(height: 12),
                                  // Form around the phone field to support validation
                                  Form(
                                    key: _formKey,
                                    child: AppTextField(
                                      controller: _phoneController,
                                      focusNode: _phoneFocusNode,
                                      keyboardType: TextInputType.phone,
                                      hintText: null,
                                      // validate phone: must be digits and at least 8 chars
                                      validator: (v) {
                                        final value = v?.trim() ?? '';
                                        if (value.isEmpty) return AppLanguage.phoneEmptyError;
                                        // Strict Algerian number pattern: ^(?:\+213|0)(5|6|7)[0-9]{8}$
                                        final pattern = r'^(?:\+213|0)(5|6|7)[0-9]{8}$';
                                        final reg = RegExp(pattern);
                                        if (!reg.hasMatch(value)) return AppLanguage.phoneInvalidError;
                                        return null;
                                      },
                                      // Disable live validation; validation will be
                                      // triggered explicitly when the Send button is pressed.
                                      autovalidateMode: AutovalidateMode.disabled,
                                      // leading is a button containing the flag and an up-arrow.
                                      leading: SizedBox(
                                        width: AppDimensions.flagButtonWidth,
                                        child: Padding(
                                          padding: const EdgeInsets.only(left: 8.0, right: 8.0),
                                          child: _FlagButton(
                                            currentAsset: 'assets/images/flags/algeria.svg',
                                            onSelected: (asset) => cubit.setCountryCode(asset),
                                            preserveFocus: _phoneFocusNode,
                                          ),
                                        ),
                                      ),
                                      onChanged: (v) => cubit.setPhoneNumber(v),
                                    ),
                                  ),

                                  // Flexible spacer pushes the following content to the bottom
                                  const Spacer(),

                                  // If focused: show consent above the button, then the button.
                                  // Otherwise: the button is hidden and consent sits at the bottom.
                                  if (_phoneFocusNode.hasFocus) ...[
                                    Align(
                                      alignment: Alignment.center,
                                      child: RichText(
                                        textAlign: TextAlign.center,
                                        text: TextSpan(
                                          style: AppTextStyles.caption.copyWith(color: Theme.of(context).colorScheme.onSurface),
                                          children: [
                                            TextSpan(text: '${AppLanguage.consentPrefix} '),
                                            TextSpan(
                                              text: AppLanguage.termsOfUse,
                                              style: const TextStyle(decoration: TextDecoration.underline),
                                            ),
                                            TextSpan(text: ' ${AppLanguage.and} '),
                                            TextSpan(
                                              text: AppLanguage.privacyPolicy,
                                              style: const TextStyle(decoration: TextDecoration.underline),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    const SizedBox(height: 12),
                                    AnimatedSwitcher(
                                      duration: const Duration(milliseconds: 200),
                                      switchInCurve: Curves.easeOut,
                                      switchOutCurve: Curves.easeIn,
                                      child: SizedBox(
                                        key: const ValueKey('send_button'),
                                        width: double.infinity,
                                        child: AppButton(
                                          text: AppLanguage.sendCode,
                                          onPressed: state.status == VerificationStatus.loading
                                              ? null
                                              : () async {
                                                  // Validate the form before sending
                                                  final valid = _formKey.currentState?.validate() ?? false;

                                                  if (!valid) return;

                                                  await cubit.sendCode();
                                                },
                                          isLoading: state.status == VerificationStatus.loading,
                                          height: 48,
                                          padding: const EdgeInsets.symmetric(horizontal: 20),
                                        ),
                                      ),
                                    ),
                                    const SizedBox(height: AppDimensions.spacingXL),
                                  ] else ...[
                                    // Hidden send button
                                    AnimatedSwitcher(
                                      duration: const Duration(milliseconds: 200),
                                      child: const SizedBox.shrink(key: ValueKey('send_button_hidden')),
                                    ),
                                    const SizedBox(height: AppDimensions.spacingXL),
                                    Align(
                                      alignment: Alignment.center,
                                      child: RichText(
                                        textAlign: TextAlign.center,
                                        text: TextSpan(
                                          style: AppTextStyles.caption.copyWith(color: Theme.of(context).colorScheme.onSurface),
                                          children: [
                                            TextSpan(text: '${AppLanguage.consentPrefix} '),
                                            TextSpan(
                                              text: AppLanguage.termsOfUse,
                                              style: const TextStyle(decoration: TextDecoration.underline),
                                            ),
                                            TextSpan(text: ' ${AppLanguage.and} '),
                                            TextSpan(
                                              text: AppLanguage.privacyPolicy,
                                              style: const TextStyle(decoration: TextDecoration.underline),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ],
                              )));
                            },
                          ),
                        ),
                      );
                    }),
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );
  }
}

class _CountryCodeSelector extends StatefulWidget {
  final String initial;
  final ValueChanged<String> onChanged;

  const _CountryCodeSelector({required this.initial, required this.onChanged});

  @override
  State<_CountryCodeSelector> createState() => _CountryCodeSelectorState();
}

class _FlagButton extends StatefulWidget {
  final String currentAsset;
  final ValueChanged<String> onSelected;
  final FocusNode? preserveFocus;

  const _FlagButton({required this.currentAsset, required this.onSelected, this.preserveFocus});

  @override
  State<_FlagButton> createState() => _FlagButtonState();
}

class _FlagButtonState extends State<_FlagButton> {
  final LayerLink _layerLink = LayerLink();
  OverlayEntry? _overlayEntry;
  final GlobalKey _buttonKey = GlobalKey();

  void _removeOverlay() {
    _overlayEntry?.remove();
    _overlayEntry = null;
  }

  void _showOverlay() {
    // Remember previous focus
    final hadFocus = widget.preserveFocus?.hasFocus ?? false;

    _overlayEntry = OverlayEntry(builder: (context) {
      // compute button height to offset the follower
      double buttonHeight = 0;
      final btnContext = _buttonKey.currentContext;
      if (btnContext != null) {
        final rb = btnContext.findRenderObject();
        if (rb is RenderBox) buttonHeight = rb.size.height;
      }

      return Positioned.fill(
        child: GestureDetector(
          behavior: HitTestBehavior.translucent,
          onTap: () {
            _removeOverlay();
            if (hadFocus && (widget.preserveFocus != null)) {
              Future.microtask(() => widget.preserveFocus!.requestFocus());
            }
          },
          child: Material(
            color: Colors.transparent,
            child: Stack(
              children: [
                CompositedTransformFollower(
                  link: _layerLink,
                  showWhenUnlinked: false,
                  offset: Offset(0, buttonHeight),
                  child: Material(
                    elevation: 8,
                    color: Theme.of(context).cardColor,
                    borderRadius: BorderRadius.circular(8),
                    child: ConstrainedBox(
                      constraints: BoxConstraints(minWidth: 150, maxWidth: 280),
                      child: IntrinsicWidth(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: List.generate(3, (i) {
                            return InkWell(
                              onTap: () {
                                widget.onSelected('assets/images/flags/algeria.svg');
                                _removeOverlay();
                                if (hadFocus && (widget.preserveFocus != null)) {
                                  Future.microtask(() => widget.preserveFocus!.requestFocus());
                                }
                              },
                              child: Padding(
                                padding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 10.0),
                                child: Row(
                                  children: [
                                    FlagImage.asset('assets/images/flags/algeria.svg', width: 28, height: 20),
                                    const SizedBox(width: 12),
                                    Text('Algeria'),
                                  ],
                                ),
                              ),
                            );
                          }),
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      );
    });

  Overlay.of(context).insert(_overlayEntry!);
  }

  @override
  void dispose() {
    _removeOverlay();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CompositedTransformTarget(
      link: _layerLink,
      child: SizedBox(
        width: double.infinity,
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            key: _buttonKey,
            borderRadius: BorderRadius.circular(8),
            onTapDown: (_) {
              try {
                widget.preserveFocus?.requestFocus();
              } catch (_) {}
            },
            onTap: () {
              // Toggle overlay
              if (_overlayEntry == null) {
                _showOverlay();
              } else {
                _removeOverlay();
              }
            },
            child: LayoutBuilder(
              builder: (context, constraints) {
                const neededWidth = 64.0; // flag(28)+spacing(8)+icon(16)+inner padding(12)
                final content = Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 6.0, vertical: 8.0),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      FlagImage.asset(widget.currentAsset, width: 28, height: 20),
                      const SizedBox(width: 8),
                      Icon(
                        Icons.keyboard_arrow_up,
                        size: 16,
                        color: Theme.of(context).iconTheme.color ?? Colors.red,
                      ),
                    ],
                  ),
                );

                if (constraints.maxWidth.isFinite && constraints.maxWidth < neededWidth) {
                  return FittedBox(fit: BoxFit.scaleDown, alignment: Alignment.centerLeft, child: content);
                }

                // Ensure the entire available width is tappable by placing the
                // content inside a Row that aligns to the start but expands.
                return Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    content,
                    const Spacer(),
                  ],
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

class _CountryCodeSelectorState extends State<_CountryCodeSelector> {
  late String _code;

  final List<Map<String, String>> _options = const [
    {'code': '+213', 'label': 'DZ'},
    {'code': '+33', 'label': 'FR'},
    {'code': '+1', 'label': 'US'},
  ];

  @override
  void initState() {
    super.initState();
    _code = widget.initial;
  }

  @override
  Widget build(BuildContext context) {
    return DropdownButtonHideUnderline(
      child: DropdownButton<String>(
        value: _code,
        items: _options
            .map((e) => DropdownMenuItem(
                  value: e['code'],
                  child: Row(
                    children: [
                      Text(e['label'] ?? ''),
                      const SizedBox(width: 6),
                      Text(e['code'] ?? ''),
                    ],
                  ),
                ))
            .toList(),
        onChanged: (v) {
          if (v == null) return;
          setState(() => _code = v);
          widget.onChanged(v);
        },
      ),
    );
  }
}
